<?php
/**
 * Custom fields: Departure CPT.
 *
 * @package quark-departures
 */

// Check if ACF function exists or not.
if ( function_exists( 'acf_add_local_field_group' ) ) :

	// Add local filed group for Departure POST.
	acf_add_local_field_group(
		[
			'key'                   => 'group_65f125e0029d3',
			'title'                 => 'Departure',
			'fields'                => [
				[
					'key'                  => 'field_65f125e02a179',
					'label'                => 'Related Expedition',
					'name'                 => 'related_expedition',
					'aria-label'           => '',
					'type'                 => 'post_object',
					'instructions'         => '',
					'required'             => 1,
					'conditional_logic'    => 0,
					'wrapper'              => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'post_type'            => [
						0 => 'expedition',
					],
					'post_status'          => '',
					'taxonomy'             => '',
					'return_format'        => 'object',
					'multiple'             => 0,
					'allow_null'           => 0,
					'bidirectional'        => 0,
					'ui'                   => 1,
					'bidirectional_target' => [],
				],
				[
					'key'                  => 'field_65f1744f2a181',
					'label'                => 'Related Ship',
					'name'                 => 'related_ship',
					'aria-label'           => '',
					'type'                 => 'post_object',
					'instructions'         => '',
					'required'             => 1,
					'conditional_logic'    => 0,
					'wrapper'              => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'post_type'            => '',
					'post_status'          => '',
					'taxonomy'             => '',
					'return_format'        => 'id',
					'multiple'             => 0,
					'allow_null'           => 0,
					'bidirectional'        => 0,
					'ui'                   => 1,
					'bidirectional_target' => [],
				],
				[
					'key'               => 'field_65f909753cb74',
					'label'             => 'Softrip',
					'name'              => 'softrip',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'layout'            => 'block',
					'sub_fields'        => [
						[
							'key'               => 'field_65f16c2b2a17b',
							'label'             => 'Departure ID',
							'name'              => 'departure_id',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'               => 'field_65f16c852a17e',
							'label'             => 'Package ID',
							'name'              => 'package_id',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'               => 'field_65f174402a180',
							'label'             => 'Tour Code',
							'name'              => 'tour_code',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
					],
				],
				[
					'key'               => 'field_65f16c4c2a17c',
					'label'             => 'Departure Start Date',
					'name'              => 'departure_start_date',
					'aria-label'        => '',
					'type'              => 'date_picker',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'display_format'    => 'd/m/Y',
					'return_format'     => 'd/m/Y',
					'first_day'         => 1,
				],
				[
					'key'               => 'field_65f16c6c2a17d',
					'label'             => 'Departure End Date',
					'name'              => 'departure_end_date',
					'aria-label'        => '',
					'type'              => 'date_picker',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'display_format'    => 'd/m/Y',
					'return_format'     => 'd/m/Y',
					'first_day'         => 1,
				],
				[
					'key'               => 'field_65f174892a182',
					'label'             => 'Duration',
					'name'              => 'duration',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => 'The length of this departure, in days.',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'min'               => 1,
					'max'               => '',
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				],
				[
					'key'                  => 'field_65f177aaa9b95',
					'label'                => 'Itinerary',
					'name'                 => 'itinerary',
					'aria-label'           => '',
					'type'                 => 'post_object',
					'instructions'         => 'Automatically populated by Softrip import.',
					'required'             => 1,
					'conditional_logic'    => 0,
					'wrapper'              => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'post_type'            => [
						0 => 'itinerary',
					],
					'post_status'          => '',
					'taxonomy'             => '',
					'return_format'        => 'object',
					'multiple'             => 0,
					'allow_null'           => 0,
					'bidirectional'        => 0,
					'ui'                   => 1,
					'bidirectional_target' => [],
				],
				[
					'key'               => 'field_65f1785fa9b96',
					'label'             => 'Expedition Team',
					'name'              => 'expedition_team',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'layout'            => 'block',
					'pagination'        => 0,
					'min'               => 0,
					'max'               => 0,
					'collapsed'         => '',
					'button_label'      => 'Add Departure Staff Member',
					'rows_per_page'     => 20,
					'sub_fields'        => [
						[
							'key'                  => 'field_65f17fb0a9b97',
							'label'                => 'Staff Member',
							'name'                 => 'staff_member',
							'aria-label'           => '',
							'type'                 => 'post_object',
							'instructions'         => '',
							'required'             => 1,
							'conditional_logic'    => 0,
							'wrapper'              => [
								'width' => '80',
								'class' => '',
								'id'    => '',
							],
							'post_type'            => [
								0 => 'qrk_staff_member',
							],
							'post_status'          => '',
							'taxonomy'             => '',
							'return_format'        => 'object',
							'multiple'             => 0,
							'allow_null'           => 0,
							'bidirectional'        => 0,
							'ui'                   => 1,
							'bidirectional_target' => [],
							'parent_repeater'      => 'field_65f1785fa9b96',
						],
						[
							'key'               => 'field_65f17fe8a9b98',
							'label'             => 'Is Special Guest?',
							'name'              => 'is_special_guest',
							'aria-label'        => '',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '20',
								'class' => '',
								'id'    => '',
							],
							'message'           => '',
							'default_value'     => 0,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
							'ui'                => 1,
							'parent_repeater'   => 'field_65f1785fa9b96',
						],
						[
							'key'                  => 'field_65f1800aa9b99',
							'label'                => 'Departure Staff Role',
							'name'                 => 'departure_staff_role',
							'aria-label'           => '',
							'type'                 => 'taxonomy',
							'instructions'         => '',
							'required'             => 0,
							'conditional_logic'    => 0,
							'wrapper'              => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'taxonomy'             => 'category',
							'add_term'             => 0,
							'save_terms'           => 0,
							'load_terms'           => 1,
							'return_format'        => 'object',
							'field_type'           => 'multi_select',
							'allow_null'           => 1,
							'bidirectional'        => 0,
							'multiple'             => 0,
							'bidirectional_target' => [],
							'parent_repeater'      => 'field_65f1785fa9b96',
						],
					],
				],
			],
			'location'              => [
				[
					[
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'qrk_departure',
					],
				],
			],
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		]
	);

	// End if condition.
endif;
