<?php
/**
 * Custom fields: Staff Members CPT.
 *
 * @package quark-staff-members
 */

// Check if ACF function exists or not.
if ( function_exists( 'acf_add_local_field_group' ) ) :

	// Add local filed group for Staff members POST.
	acf_add_local_field_group(
		[
			'key'                   => 'group_65f44723ae0a1',
			'title'                 => 'Staff Member',
			'fields'                => [
				[
					'key'               => 'field_65f44f76bd933',
					'label'             => 'Job Title (Role)',
					'name'              => 'job_title',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Used for head office (non-expedition team roles). If no expedition team role is entered, website will fall back to using this value.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				],
				[
					'key'               => 'field_65f44724bd997',
					'label'             => 'Personal Information',
					'name'              => 'personal_information',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'layout'            => 'block',
					'sub_fields'        => [
						[
							'key'               => 'field_65f44781bd998',
							'label'             => 'First Name',
							'name'              => 'first_name',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'               => 'field_65f4478bbd999',
							'label'             => 'Last Name',
							'name'              => 'last_name',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'               => 'field_65f44797bd99a',
							'label'             => 'Hometown',
							'name'              => 'hometown',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'               => 'field_65f4481abd99c',
							'label'             => 'Years with Quark',
							'name'              => 'years_with_quark',
							'aria-label'        => '',
							'type'              => 'date_picker',
							'instructions'      => 'Enter date the employee started working at Quark.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'display_format'    => 'd/m/Y',
							'return_format'     => 'd/m/Y',
							'first_day'         => 1,
						],
						[
							'key'               => 'field_65f4487ebd99d',
							'label'             => 'Expeditions Completed',
							'name'              => 'expeditions_completed',
							'aria-label'        => '',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'min'               => '',
							'max'               => '',
							'placeholder'       => '',
							'step'              => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'               => 'field_65f4488bbd99e',
							'label'             => 'Countries Travelled',
							'name'              => 'countries_travelled',
							'aria-label'        => '',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'min'               => '',
							'max'               => '',
							'placeholder'       => '',
							'step'              => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'                  => 'field_65f4489abd99f',
							'label'                => 'Favorite Destination',
							'name'                 => 'favorite_destination',
							'aria-label'           => '',
							'type'                 => 'post_object',
							'instructions'         => '',
							'required'             => 0,
							'conditional_logic'    => 0,
							'wrapper'              => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'post_type'            => [
								0 => 'region_landing_page',
							],
							'post_status'          => '',
							'taxonomy'             => '',
							'return_format'        => 'id',
							'multiple'             => 0,
							'allow_null'           => 0,
							'bidirectional'        => 0,
							'ui'                   => 1,
							'bidirectional_target' => [],
						],
						[
							'key'                  => 'field_65f448d2bd9a0',
							'label'                => 'Favorite Ship',
							'name'                 => 'favorite_ship',
							'aria-label'           => '',
							'type'                 => 'post_object',
							'instructions'         => '',
							'required'             => 0,
							'conditional_logic'    => 0,
							'wrapper'              => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'post_type'            => [
								0 => 'ship',
							],
							'post_status'          => '',
							'taxonomy'             => '',
							'return_format'        => 'id',
							'multiple'             => 0,
							'allow_null'           => 0,
							'bidirectional'        => 0,
							'ui'                   => 1,
							'bidirectional_target' => [],
						],
					],
				],
				[
					'key'               => 'field_65f44cb31752c',
					'label'             => 'Video URL',
					'name'              => 'video_url',
					'aria-label'        => '',
					'type'              => 'url',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'placeholder'       => '',
				],
				[
					'key'               => 'field_65f44d331752f',
					'label'             => 'Contact Information',
					'name'              => 'contact_information',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'layout'            => 'block',
					'sub_fields'        => [
						[
							'key'               => 'field_65f44d6317530',
							'label'             => 'Email Address',
							'name'              => 'email_address',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'               => 'field_65f44d6c17531',
							'label'             => 'Phone Extension',
							'name'              => 'phone_extension',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '20',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'               => 'field_65f44d8b17532',
							'label'             => 'Phone Number',
							'name'              => 'phone_number',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '60',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
					],
				],
			],
			'location'              => [
				[
					[
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'qrk_staff_member',
					],
				],
			],
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		],
	);

	// End if condition.
endif;
