<?php
/**
 * Custom fields: Cabin Categories.
 *
 * @package quark-cabin-categories
 */

// Check if ACF function exists or not.
if ( function_exists( 'acf_add_local_field_group' ) ) :

	// Add local filed group for Cabin categories POST.
	acf_add_local_field_group(
		[
			'key'                   => 'group_65f8191003918',
			'title'                 => 'Cabin Category',
			'fields'                => [
				[
					'key'               => 'field_65f8191043707',
					'label'             => 'Cabin Name',
					'name'              => 'cabin_name',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Cabin name for listing and cards.',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				],
				[
					'key'               => 'field_65f8196602f53',
					'label'             => 'Cabin Category ID',
					'name'              => 'cabin_category_id',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => 'Cabin category ID used by SOFTRIP API.',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				],
				[
					'key'                  => 'field_65f819ca02f54',
					'label'                => 'Related Ship',
					'name'                 => 'related_ship',
					'aria-label'           => '',
					'type'                 => 'post_object',
					'instructions'         => 'Please choose the ship to which the cabin is available.',
					'required'             => 1,
					'conditional_logic'    => 0,
					'wrapper'              => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'post_type'            => [
						0 => 'qrk_ship',
					],
					'post_status'          => '',
					'taxonomy'             => '',
					'return_format'        => 'object',
					'multiple'             => 0,
					'allow_null'           => 0,
					'bidirectional'        => 0,
					'ui'                   => 1,
					'bidirectional_target' => [],
				],
				[
					'key'                  => 'field_65f81a3502f55',
					'label'                => 'Related Decks',
					'name'                 => 'related_decks',
					'aria-label'           => '',
					'type'                 => 'relationship',
					'instructions'         => '',
					'required'             => 1,
					'conditional_logic'    => 0,
					'wrapper'              => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'post_type'            => [
						0 => 'qrk_ship_deck',
					],
					'post_status'          => '',
					'taxonomy'             => '',
					'filters'              => [
						0 => 'search',
					],
					'return_format'        => 'object',
					'min'                  => '',
					'max'                  => '',
					'elements'             => '',
					'bidirectional'        => 0,
					'bidirectional_target' => [],
				],
				[
					'key'               => 'field_65f81a8a02f56',
					'label'             => 'Legend Color',
					'name'              => 'legend_color',
					'aria-label'        => '',
					'type'              => 'color_picker',
					'instructions'      => 'The color used to indicate this cabin category in deck plan drawings.',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'enable_opacity'    => 0,
					'return_format'     => 'string',
				],
				[
					'key'               => 'field_65f81b2661e3c',
					'label'             => 'Cabin Category Size Range',
					'name'              => 'cabin_category_size_range',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'layout'            => 'block',
					'sub_fields'        => [
						[
							'key'               => 'field_65f81b9661e3d',
							'label'             => 'From',
							'name'              => 'from',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '50',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => 'sq. ft.',
						],
						[
							'key'               => 'field_65f81bba61e3e',
							'label'             => 'To',
							'name'              => 'to',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '50',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => 'sq. ft.',
						],
					],
				],
				[
					'key'               => 'field_65f81c0661e3f',
					'label'             => 'Cabin Occupancy Pax Range',
					'name'              => 'cabin_occupancy_pax_range',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'layout'            => 'block',
					'sub_fields'        => [
						[
							'key'               => 'field_65f81c0661e40',
							'label'             => 'From',
							'name'              => 'from',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '50',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => 'passengers',
						],
						[
							'key'               => 'field_65f81c0661e41',
							'label'             => 'To',
							'name'              => 'to',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '50',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => 'passengers',
						],
					],
				],
				[
					'key'               => 'field_65f81c3061e42',
					'label'             => 'Cabin Bed Configuration',
					'name'              => 'cabin_bed_configuration',
					'aria-label'        => '',
					'type'              => 'wysiwyg',
					'instructions'      => 'Examples: <br/>- 2 lower berths <br/>- 2 lower berths, 1 Pullman <br/>- 1 double bed made of two single berths',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 1,
				],
				[
					'key'               => 'field_65f8232838c1c',
					'label'             => 'Cabin Images',
					'name'              => 'cabin_images',
					'aria-label'        => '',
					'type'              => 'gallery',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'return_format'     => 'array',
					'library'           => 'all',
					'min'               => 1,
					'max'               => '',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'insert'            => 'append',
					'preview_size'      => 'medium',
				],
				[
					'key'               => 'field_65f8236238c1d',
					'label'             => 'Cabin Category Cabin Count',
					'name'              => 'cabin_category_cabin_count',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => 'The number of cabins that are found in this cabin category.<br/> Dev note: This field may be temporary until all cabins can be entered as cabin nodes. Then we could get the cabin count programmatically via query, etc.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				],
				[
					'key'               => 'field_65f8239e38c1e',
					'label'             => 'Low Inventory Threshold',
					'name'              => 'low_inventory_threshold',
					'aria-label'        => '',
					'type'              => 'number',
					'instructions'      => 'The number of cabins remaining at which we consider "low" inventory in order to display urgency messaging, etc.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'min'               => '',
					'max'               => '',
					'placeholder'       => '',
					'step'              => '',
					'prepend'           => '',
					'append'            => '',
				],
			],
			'location'              => [
				[
					[
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'qrk_cabin_category',
					],
				],
			],
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		]
	);

	// End if condition.
endif;
