<?php
/**
 * Custom fields: Itinerary Day CPT.
 *
 * @package quark-itinerary-days
 */

// Check if ACF function exists or not.
if ( function_exists( 'acf_add_local_field_group' ) ) :

	// Add local filed group for Itinerary Day POST.
	acf_add_local_field_group(
		[
			'key'                   => 'group_65f4593f1480e',
			'title'                 => 'Itinerary Days',
			'fields'                => [
				[
					'key'               => 'field_65f4593f84a43',
					'label'             => 'Day Title',
					'name'              => 'day_title',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				],
				[
					'key'               => 'field_65f8393e45ae4',
					'label'             => 'Description',
					'name'              => 'description',
					'aria-label'        => '',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'delay'             => 1,
				],
				[
					'key'               => 'field_65f4596c84a44',
					'label'             => 'Start / End Day Numbers',
					'name'              => 'day_numbers',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'layout'            => 'block',
					'sub_fields'        => [
						[
							'key'               => 'field_65f4598484a45',
							'label'             => 'From',
							'name'              => 'from',
							'aria-label'        => '',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '50',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => 1,
							'min'               => '',
							'max'               => '',
							'placeholder'       => '',
							'step'              => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'               => 'field_65f459ab84a47',
							'label'             => 'To',
							'name'              => 'to',
							'aria-label'        => '',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '50',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => 1,
							'min'               => '',
							'max'               => '',
							'placeholder'       => '',
							'step'              => '',
							'prepend'           => '',
							'append'            => '',
						],
					],
				],
				[
					'key'                  => 'field_65fc55776c6e4',
					'label'                => 'Port',
					'name'                 => 'port',
					'aria-label'           => '',
					'type'                 => 'post_object',
					'instructions'         => '',
					'required'             => 0,
					'conditional_logic'    => 0,
					'wrapper'              => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'post_type'            => [
						0 => 'qrk_port',
					],
					'post_status'          => '',
					'taxonomy'             => '',
					'return_format'        => 'object',
					'multiple'             => 0,
					'allow_null'           => 0,
					'bidirectional'        => 0,
					'ui'                   => 1,
					'bidirectional_target' => [],
				],
				[
					'key'               => 'field_65f459fa84a49',
					'label'             => 'Location',
					'name'              => 'location',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '50',
						'class' => '',
						'id'    => '',
					],
					'default_value'     => '',
					'maxlength'         => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				],
				[
					'key'               => 'field_65f45a1684a4a',
					'label'             => 'Geocoordinates',
					'name'              => 'geocoordinate',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => [
						'width' => '',
						'class' => '',
						'id'    => '',
					],
					'layout'            => 'block',
					'sub_fields'        => [
						[
							'key'               => 'field_65f45a1f84a4b',
							'label'             => 'Latitude',
							'name'              => 'latitude',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => 'Enter either in decimal 51.47879 or sexagesimal format 51° 28\' 43.644"',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '50',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
						[
							'key'               => 'field_65f45a3784a4c',
							'label'             => 'Longitude',
							'name'              => 'longitude',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => 'Enter either in decimal -0.010677 or sexagesimal format -0° 38.4372"',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => [
								'width' => '50',
								'class' => '',
								'id'    => '',
							],
							'default_value'     => '',
							'maxlength'         => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
						],
					],
				],
			],
			'location'              => [
				[
					[
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'qrk_itinerary_day',
					],
				],
			],
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		],
	);

	// End if condition.
endif;
