name: Ingestor Urgent Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Pantheon Environment'
        required: true
        default: 'development'

jobs:
  ingestor-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer, cs2pr

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Run ingestor urgent push
        env:
          PANTHEON_SSH_PRIVATE_KEY: ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}
        run: |
          if [ "${{ github.event.inputs.environment }}" = "development" ]; then
            bash .bin/ingestor-urgent-push-qa.sh
          elif [ "${{ github.event.inputs.environment }}" = "staging" ]; then
            bash .bin/ingestor-urgent-push-staging.sh
          elif [ "${{ github.event.inputs.environment }}" = "production" ]; then
            bash .bin/ingestor-urgent-push-production.sh
          else
            echo "Invalid environment: ${{ github.event.inputs.environment }}"
            exit 1
          fi
