name: Deploy to Production

concurrency: production

on: workflow_dispatch

permissions:
  contents: read

jobs:
  pre-run:
    name: Pre-Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check allowed user
        run: |
          USER_EXISTS=$(jq -r --arg key "$GITHUB_ACTOR" '.allowed_sync_users | any(. == $key)' .github/users.json)
          if [ "$USER_EXISTS" = "false" ]; then
            echo "::error::$GITHUB_ACTOR is not allowed to deploy to production"
            exit 1
          fi

  deploy:
    name: Deploy code from staging to production
    needs: pre-run
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      PANTHEON_SSH_PRIVATE_KEY: ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Deploy to production
        run: bash .bin/deploy-to-production.sh