name: WordPress Cron (Staging)

on:
  schedule:
    - cron: '15 * * * *' # Avoid high load time by loading later: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

jobs:
  wp-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer, cs2pr

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

      - name: Run WordPress Cron
        env:
          PANTHEON_SSH_PRIVATE_KEY: ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}
        run: bash .bin/cron-staging.sh
